# Generated by Django 4.2 on 2023-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphotos',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фотографии продуктов'},
        ),
        migrations.AlterField(
            model_name='brandproduct',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/brand/'),
        ),
    ]
