# Generated by Django 4.2 on 2023-04-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productphotos_options_alter_brandproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='type',
            field=models.ManyToManyField(blank=True, to='store.typeproduct'),
        ),
    ]
