# Generated by Django 4.2 on 2023-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_categoryproduct_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='brand',
            field=models.ManyToManyField(blank=True, to='store.brandproduct'),
        ),
    ]
