# Generated by Django 4.2 on 2023-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, to='store.categoryproduct'),
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='type',
            field=models.ManyToManyField(blank=True, to='store.typeproduct'),
        ),
    ]
